//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_CourseCate
    {
        public int CourseCourseCateID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> CourseCateID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual CourseCate CourseCate { get; set; }
    }
}
