//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingStaff_Trainee
    {
        public int TrainingStaffTraineeID { get; set; }
        public Nullable<int> TrainingStaffID { get; set; }
        public Nullable<int> TraineeID { get; set; }
    
        public virtual Trainee Trainee { get; set; }
        public virtual TrainingStaff TrainingStaff { get; set; }
    }
}
